DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
WARNING | Not Found: /
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | validated data: {'first_name': 'Ibrahimji', 'last_name': 'Khaleelji', 'email': 'itisnoteasy@gmail.com', 'user_name': 'differentuser'}
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
<<<<<<< HEAD
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundooNotes\migrations\0001_initial.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\manage.py changed, reloading.
=======
DEBUG | Importing BlpImagePlugin
DEBUG | Importing BmpImagePlugin
DEBUG | Importing BufrStubImagePlugin
DEBUG | Importing CurImagePlugin
DEBUG | Importing DcxImagePlugin
DEBUG | Importing DdsImagePlugin
DEBUG | Importing EpsImagePlugin
DEBUG | Importing FitsStubImagePlugin
DEBUG | Importing FliImagePlugin
DEBUG | Importing FpxImagePlugin
DEBUG | Image: failed to import FpxImagePlugin: No module named 'olefile'
DEBUG | Importing FtexImagePlugin
DEBUG | Importing GbrImagePlugin
DEBUG | Importing GifImagePlugin
DEBUG | Importing GribStubImagePlugin
DEBUG | Importing Hdf5StubImagePlugin
DEBUG | Importing IcnsImagePlugin
DEBUG | Importing IcoImagePlugin
DEBUG | Importing ImImagePlugin
DEBUG | Importing ImtImagePlugin
DEBUG | Importing IptcImagePlugin
DEBUG | Importing JpegImagePlugin
DEBUG | Importing Jpeg2KImagePlugin
DEBUG | Importing McIdasImagePlugin
DEBUG | Importing MicImagePlugin
DEBUG | Image: failed to import MicImagePlugin: No module named 'olefile'
DEBUG | Importing MpegImagePlugin
DEBUG | Importing MpoImagePlugin
DEBUG | Importing MspImagePlugin
DEBUG | Importing PalmImagePlugin
DEBUG | Importing PcdImagePlugin
DEBUG | Importing PcxImagePlugin
DEBUG | Importing PdfImagePlugin
DEBUG | Importing PixarImagePlugin
DEBUG | Importing PngImagePlugin
DEBUG | Importing PpmImagePlugin
DEBUG | Importing PsdImagePlugin
DEBUG | Importing SgiImagePlugin
DEBUG | Importing SpiderImagePlugin
DEBUG | Importing SunImagePlugin
DEBUG | Importing TgaImagePlugin
DEBUG | Importing TiffImagePlugin
DEBUG | Importing WebPImagePlugin
DEBUG | Importing WmfImagePlugin
DEBUG | Importing XbmImagePlugin
DEBUG | Importing XpmImagePlugin
DEBUG | Importing XVThumbImagePlugin
DEBUG | Using proactor: IocpProactor
DEBUG | Importing BlpImagePlugin
DEBUG | Importing BmpImagePlugin
DEBUG | Importing BufrStubImagePlugin
DEBUG | Importing CurImagePlugin
DEBUG | Importing DcxImagePlugin
DEBUG | Importing DdsImagePlugin
DEBUG | Importing EpsImagePlugin
DEBUG | Importing FitsStubImagePlugin
DEBUG | Importing FliImagePlugin
DEBUG | Importing FpxImagePlugin
DEBUG | Image: failed to import FpxImagePlugin: No module named 'olefile'
DEBUG | Importing FtexImagePlugin
DEBUG | Importing GbrImagePlugin
DEBUG | Importing GifImagePlugin
DEBUG | Importing GribStubImagePlugin
DEBUG | Importing Hdf5StubImagePlugin
DEBUG | Importing IcnsImagePlugin
DEBUG | Importing IcoImagePlugin
DEBUG | Importing ImImagePlugin
DEBUG | Importing ImtImagePlugin
DEBUG | Importing IptcImagePlugin
DEBUG | Importing JpegImagePlugin
DEBUG | Importing Jpeg2KImagePlugin
DEBUG | Importing McIdasImagePlugin
DEBUG | Importing MicImagePlugin
DEBUG | Image: failed to import MicImagePlugin: No module named 'olefile'
DEBUG | Importing MpegImagePlugin
DEBUG | Importing MpoImagePlugin
DEBUG | Importing MspImagePlugin
DEBUG | Importing PalmImagePlugin
DEBUG | Importing PcdImagePlugin
DEBUG | Importing PcxImagePlugin
DEBUG | Importing PdfImagePlugin
DEBUG | Importing PixarImagePlugin
DEBUG | Importing PngImagePlugin
DEBUG | Importing PpmImagePlugin
DEBUG | Importing PsdImagePlugin
DEBUG | Importing SgiImagePlugin
DEBUG | Importing SpiderImagePlugin
DEBUG | Importing SunImagePlugin
DEBUG | Importing TgaImagePlugin
DEBUG | Importing TiffImagePlugin
DEBUG | Importing WebPImagePlugin
DEBUG | Importing WmfImagePlugin
DEBUG | Importing XbmImagePlugin
DEBUG | Importing XpmImagePlugin
DEBUG | Importing XVThumbImagePlugin
WARNING | Not Found: /images/note_images/PIPI6214.JPG
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\settings.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Not Found: /
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Importing BlpImagePlugin
DEBUG | Importing BmpImagePlugin
DEBUG | Importing BufrStubImagePlugin
DEBUG | Importing CurImagePlugin
DEBUG | Importing DcxImagePlugin
DEBUG | Importing DdsImagePlugin
DEBUG | Importing EpsImagePlugin
DEBUG | Importing FitsStubImagePlugin
DEBUG | Importing FliImagePlugin
DEBUG | Importing FpxImagePlugin
DEBUG | Image: failed to import FpxImagePlugin: No module named 'olefile'
DEBUG | Importing FtexImagePlugin
DEBUG | Importing GbrImagePlugin
DEBUG | Importing GifImagePlugin
DEBUG | Importing GribStubImagePlugin
DEBUG | Importing Hdf5StubImagePlugin
DEBUG | Importing IcnsImagePlugin
DEBUG | Importing IcoImagePlugin
DEBUG | Importing ImImagePlugin
DEBUG | Importing ImtImagePlugin
DEBUG | Importing IptcImagePlugin
DEBUG | Importing JpegImagePlugin
DEBUG | Importing Jpeg2KImagePlugin
DEBUG | Importing McIdasImagePlugin
DEBUG | Importing MicImagePlugin
DEBUG | Image: failed to import MicImagePlugin: No module named 'olefile'
DEBUG | Importing MpegImagePlugin
DEBUG | Importing MpoImagePlugin
DEBUG | Importing MspImagePlugin
DEBUG | Importing PalmImagePlugin
DEBUG | Importing PcdImagePlugin
DEBUG | Importing PcxImagePlugin
DEBUG | Importing PdfImagePlugin
DEBUG | Importing PixarImagePlugin
DEBUG | Importing PngImagePlugin
DEBUG | Importing PpmImagePlugin
DEBUG | Importing PsdImagePlugin
DEBUG | Importing SgiImagePlugin
DEBUG | Importing SpiderImagePlugin
DEBUG | Importing SunImagePlugin
DEBUG | Importing TgaImagePlugin
DEBUG | Importing TiffImagePlugin
DEBUG | Importing WebPImagePlugin
DEBUG | Importing WmfImagePlugin
DEBUG | Importing XbmImagePlugin
DEBUG | Importing XpmImagePlugin
DEBUG | Importing XVThumbImagePlugin
WARNING | Not Found: /images/childhood.jpg
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\settings.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\settings.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Importing BlpImagePlugin
DEBUG | Importing BmpImagePlugin
DEBUG | Importing BufrStubImagePlugin
DEBUG | Importing CurImagePlugin
DEBUG | Importing DcxImagePlugin
DEBUG | Importing DdsImagePlugin
DEBUG | Importing EpsImagePlugin
DEBUG | Importing FitsStubImagePlugin
DEBUG | Importing FliImagePlugin
DEBUG | Importing FpxImagePlugin
DEBUG | Image: failed to import FpxImagePlugin: No module named 'olefile'
DEBUG | Importing FtexImagePlugin
DEBUG | Importing GbrImagePlugin
DEBUG | Importing GifImagePlugin
DEBUG | Importing GribStubImagePlugin
DEBUG | Importing Hdf5StubImagePlugin
DEBUG | Importing IcnsImagePlugin
DEBUG | Importing IcoImagePlugin
DEBUG | Importing ImImagePlugin
DEBUG | Importing ImtImagePlugin
DEBUG | Importing IptcImagePlugin
DEBUG | Importing JpegImagePlugin
DEBUG | Importing Jpeg2KImagePlugin
DEBUG | Importing McIdasImagePlugin
DEBUG | Importing MicImagePlugin
DEBUG | Image: failed to import MicImagePlugin: No module named 'olefile'
DEBUG | Importing MpegImagePlugin
DEBUG | Importing MpoImagePlugin
DEBUG | Importing MspImagePlugin
DEBUG | Importing PalmImagePlugin
DEBUG | Importing PcdImagePlugin
DEBUG | Importing PcxImagePlugin
DEBUG | Importing PdfImagePlugin
DEBUG | Importing PixarImagePlugin
DEBUG | Importing PngImagePlugin
DEBUG | Importing PpmImagePlugin
DEBUG | Importing PsdImagePlugin
DEBUG | Importing SgiImagePlugin
DEBUG | Importing SpiderImagePlugin
DEBUG | Importing SunImagePlugin
DEBUG | Importing TgaImagePlugin
DEBUG | Importing TiffImagePlugin
DEBUG | Importing WebPImagePlugin
DEBUG | Importing WmfImagePlugin
DEBUG | Importing XbmImagePlugin
DEBUG | Importing XpmImagePlugin
DEBUG | Importing XVThumbImagePlugin
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Note\migrations\0002_auto_20201214_2150.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Note\migrations\0002_auto_20201214_2150.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
WARNING | Not Found: /
WARNING | Not Found: /favicon.ico
WARNING | Not Found: /
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Method Not Allowed: /note-create/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Method Not Allowed: /label-delete/1/
WARNING | Method Not Allowed: /label-delete/1/
WARNING | Method Not Allowed: /label-create/
WARNING | Not Found: /node-create/
WARNING | Method Not Allowed: /note-create/
WARNING | Method Not Allowed: /note-update/1/
WARNING | Not Found: /create-notes/
WARNING | Method Not Allowed: /note-create/
DEBUG | Importing BlpImagePlugin
DEBUG | Importing BmpImagePlugin
DEBUG | Importing BufrStubImagePlugin
DEBUG | Importing CurImagePlugin
DEBUG | Importing DcxImagePlugin
DEBUG | Importing DdsImagePlugin
DEBUG | Importing EpsImagePlugin
DEBUG | Importing FitsStubImagePlugin
DEBUG | Importing FliImagePlugin
DEBUG | Importing FpxImagePlugin
DEBUG | Image: failed to import FpxImagePlugin: No module named 'olefile'
DEBUG | Importing FtexImagePlugin
DEBUG | Importing GbrImagePlugin
DEBUG | Importing GifImagePlugin
DEBUG | Importing GribStubImagePlugin
DEBUG | Importing Hdf5StubImagePlugin
DEBUG | Importing IcnsImagePlugin
DEBUG | Importing IcoImagePlugin
DEBUG | Importing ImImagePlugin
DEBUG | Importing ImtImagePlugin
DEBUG | Importing IptcImagePlugin
DEBUG | Importing JpegImagePlugin
DEBUG | Importing Jpeg2KImagePlugin
DEBUG | Importing McIdasImagePlugin
DEBUG | Importing MicImagePlugin
DEBUG | Image: failed to import MicImagePlugin: No module named 'olefile'
DEBUG | Importing MpegImagePlugin
DEBUG | Importing MpoImagePlugin
DEBUG | Importing MspImagePlugin
DEBUG | Importing PalmImagePlugin
DEBUG | Importing PcdImagePlugin
DEBUG | Importing PcxImagePlugin
DEBUG | Importing PdfImagePlugin
DEBUG | Importing PixarImagePlugin
DEBUG | Importing PngImagePlugin
DEBUG | Importing PpmImagePlugin
DEBUG | Importing PsdImagePlugin
DEBUG | Importing SgiImagePlugin
DEBUG | Importing SpiderImagePlugin
DEBUG | Importing SunImagePlugin
DEBUG | Importing TgaImagePlugin
DEBUG | Importing TiffImagePlugin
DEBUG | Importing WebPImagePlugin
DEBUG | Importing WmfImagePlugin
DEBUG | Importing XbmImagePlugin
DEBUG | Importing XpmImagePlugin
DEBUG | Importing XVThumbImagePlugin
ERROR | Internal Server Error: /note-create/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\renderers.py", line 680, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\renderers.py", line 413, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "c:\users\ibrahim khaleel\appdata\local\programs\python\python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\ibrahim khaleel\appdata\local\programs\python\python39\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "c:\users\ibrahim khaleel\appdata\local\programs\python\python39\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "c:\users\ibrahim khaleel\appdata\local\programs\python\python39\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "c:\users\ibrahim khaleel\appdata\local\programs\python\python39\lib\json\encoder.py", line 439, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "c:\users\ibrahim khaleel\appdata\local\programs\python\python39\lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "c:\users\ibrahim khaleel\appdata\local\programs\python\python39\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "c:\users\ibrahim khaleel\appdata\local\programs\python\python39\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\utils\encoders.py", line 50, in default
    return obj.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
ERROR | Internal Server Error: /admin/Notes/note/1/change/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 698, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\defaultfilters.py", line 42, in _dec
    args[0] = str(args[0])
TypeError: __str__ returned non-string (type User)
ERROR | Internal Server Error: /admin/Notes/note/2/change/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 698, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\defaultfilters.py", line 42, in _dec
    args[0] = str(args[0])
TypeError: __str__ returned non-string (type User)
ERROR | Internal Server Error: /admin/Notes/note/2/change/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\base.py", line 698, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\template\defaultfilters.py", line 42, in _dec
    args[0] = str(args[0])
TypeError: __str__ returned non-string (type User)
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\settings.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\settings.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\settings.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Not Found: /favicon.ico
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Not Found: /label/2/
WARNING | Not Found: /label/2
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
WARNING | Not Found: /label-update/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Not Found: /label-update/
WARNING | Not Found: /label-update/
ERROR | Internal Server Error: /label-update/1/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 59, in get
    label = Label.objects.get(id = pk)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 429, in get
    raise self.model.DoesNotExist(
Label.models.Label.DoesNotExist: Label matching query does not exist.
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Not Found: /label/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
WARNING | Method Not Allowed: /register/
WARNING | Method Not Allowed: /register/
DEBUG | Using proactor: IocpProactor
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
WARNING | Not Found: /regiter/
WARNING | Method Not Allowed: /register/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleelem@gmail.com', 'user_name': 'ibrahimkhaleel'}
DEBUG | user activation successful
DEBUG | Importing BlpImagePlugin
DEBUG | Importing BmpImagePlugin
DEBUG | Importing BufrStubImagePlugin
DEBUG | Importing CurImagePlugin
DEBUG | Importing DcxImagePlugin
DEBUG | Importing DdsImagePlugin
DEBUG | Importing EpsImagePlugin
DEBUG | Importing FitsStubImagePlugin
DEBUG | Importing FliImagePlugin
DEBUG | Importing FpxImagePlugin
DEBUG | Image: failed to import FpxImagePlugin: No module named 'olefile'
DEBUG | Importing FtexImagePlugin
DEBUG | Importing GbrImagePlugin
DEBUG | Importing GifImagePlugin
DEBUG | Importing GribStubImagePlugin
DEBUG | Importing Hdf5StubImagePlugin
DEBUG | Importing IcnsImagePlugin
DEBUG | Importing IcoImagePlugin
DEBUG | Importing ImImagePlugin
DEBUG | Importing ImtImagePlugin
DEBUG | Importing IptcImagePlugin
DEBUG | Importing JpegImagePlugin
DEBUG | Importing Jpeg2KImagePlugin
DEBUG | Importing McIdasImagePlugin
DEBUG | Importing MicImagePlugin
DEBUG | Image: failed to import MicImagePlugin: No module named 'olefile'
DEBUG | Importing MpegImagePlugin
DEBUG | Importing MpoImagePlugin
DEBUG | Importing MspImagePlugin
DEBUG | Importing PalmImagePlugin
DEBUG | Importing PcdImagePlugin
DEBUG | Importing PcxImagePlugin
DEBUG | Importing PdfImagePlugin
DEBUG | Importing PixarImagePlugin
DEBUG | Importing PngImagePlugin
DEBUG | Importing PpmImagePlugin
DEBUG | Importing PsdImagePlugin
DEBUG | Importing SgiImagePlugin
DEBUG | Importing SpiderImagePlugin
DEBUG | Importing SunImagePlugin
DEBUG | Importing TgaImagePlugin
DEBUG | Importing TiffImagePlugin
DEBUG | Importing WebPImagePlugin
DEBUG | Importing WmfImagePlugin
DEBUG | Importing XbmImagePlugin
DEBUG | Importing XpmImagePlugin
DEBUG | Importing XVThumbImagePlugin
WARNING | Not Found: /media/notes/g2.jpg
WARNING | Not Found: /note-update/
WARNING | Not Found: /note-update/
WARNING | Not Found: /note-update/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\serializers.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Not Found: /note-create/
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note/
WARNING | Bad Request: /note/
WARNING | Bad Request: /note/
WARNING | Bad Request: /note/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note/
WARNING | Bad Request: /note/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note/
WARNING | Bad Request: /note/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Method Not Allowed: /login/
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
WARNING | Method Not Allowed: /register/
WARNING | Bad Request: /register/
DEBUG | validated data: {'first_name': 'Saeed', 'last_name': 'salman', 'email': 'sayYou@gmail.com', 'user_name': 'saweyou'}
DEBUG | Using proactor: IocpProactor
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
WARNING | Bad Request: /register/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
WARNING | Bad Request: /register/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
WARNING | Bad Request: /login/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
WARNING | Bad Request: /register/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note/
WARNING | Bad Request: /note/
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/7/
WARNING | Bad Request: /note-update/7/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
WARNING | Bad Request: /login/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ikhaleel@gmail.com', 'user_name': 'ibrhkhaleel'}
WARNING | Bad Request: /register/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
WARNING | Bad Request: /login/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
WARNING | Bad Request: /register/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundooNotes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundooNotes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundooNotes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\settings.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\settings.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
WARNING | Unauthorized: /login/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
WARNING | Bad Request: /register/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
WARNING | Method Not Allowed: /register/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
DEBUG | Importing BlpImagePlugin
DEBUG | Importing BmpImagePlugin
DEBUG | Importing BufrStubImagePlugin
DEBUG | Importing CurImagePlugin
DEBUG | Importing DcxImagePlugin
DEBUG | Importing DdsImagePlugin
DEBUG | Importing EpsImagePlugin
DEBUG | Importing FitsStubImagePlugin
DEBUG | Importing FliImagePlugin
DEBUG | Importing FpxImagePlugin
DEBUG | Image: failed to import FpxImagePlugin: No module named 'olefile'
DEBUG | Importing FtexImagePlugin
DEBUG | Importing GbrImagePlugin
DEBUG | Importing GifImagePlugin
DEBUG | Importing GribStubImagePlugin
DEBUG | Importing Hdf5StubImagePlugin
DEBUG | Importing IcnsImagePlugin
DEBUG | Importing IcoImagePlugin
DEBUG | Importing ImImagePlugin
DEBUG | Importing ImtImagePlugin
DEBUG | Importing IptcImagePlugin
DEBUG | Importing JpegImagePlugin
DEBUG | Importing Jpeg2KImagePlugin
DEBUG | Importing McIdasImagePlugin
DEBUG | Importing MicImagePlugin
DEBUG | Image: failed to import MicImagePlugin: No module named 'olefile'
DEBUG | Importing MpegImagePlugin
DEBUG | Importing MpoImagePlugin
DEBUG | Importing MspImagePlugin
DEBUG | Importing PalmImagePlugin
DEBUG | Importing PcdImagePlugin
DEBUG | Importing PcxImagePlugin
DEBUG | Importing PdfImagePlugin
DEBUG | Importing PixarImagePlugin
DEBUG | Importing PngImagePlugin
DEBUG | Importing PpmImagePlugin
DEBUG | Importing PsdImagePlugin
DEBUG | Importing SgiImagePlugin
DEBUG | Importing SpiderImagePlugin
DEBUG | Importing SunImagePlugin
DEBUG | Importing TgaImagePlugin
DEBUG | Importing TiffImagePlugin
DEBUG | Importing WebPImagePlugin
DEBUG | Importing WmfImagePlugin
DEBUG | Importing XbmImagePlugin
DEBUG | Importing XpmImagePlugin
DEBUG | Importing XVThumbImagePlugin
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
WARNING | Not Found: /accounts/login/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
WARNING | Not Found: /accounts/login/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
WARNING | Not Found: /accounts/login/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\settings.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\myfundoonote\settings.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | validated data: {'first_name': 'Ibraheeem', 'last_name': 'Khaleeel', 'email': 'ibrahee@gmail.com', 'user_name': 'ibrahikhaleel'}
WARNING | Not Found: /accounts/login/
DEBUG | validated data: {'first_name': 'Ibraheeem', 'last_name': 'Khaleeel', 'email': 'ibrahee@gmail.com', 'user_name': 'ibrahikhaleel'}
WARNING | Not Found: /accounts/login/
DEBUG | validated data: {'first_name': 'Ibraheeem', 'last_name': 'Khaleeel', 'email': 'ibrahee@gmail.com', 'user_name': 'ibrahikhaleel'}
DEBUG | validated data: {'first_name': 'Ibraheeem', 'last_name': 'Khaleeel', 'email': 'ibrahee@gmail.com', 'user_name': 'ibrahikhaleel'}
WARNING | Not Found: /accounts/login/
WARNING | Not Found: /accounts/login/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
WARNING | Unauthorized: /login/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
WARNING | Bad Request: /register/
DEBUG | validated data: {'first_name': 'Ibraheem', 'last_name': 'Khaleel', 'email': 'ibrah@gmail.com', 'user_name': 'ibrahkhaleel'}
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/1/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/5/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/1/
ERROR | Internal Server Error: /note/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
DEBUG | validated data: {'first_name': 'Ibraheeem', 'last_name': 'Khaleeel', 'email': 'ibrahee@gmail.com', 'user_name': 'ibrahikhaleel'}
ERROR | Internal Server Error: /note/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /note/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
DEBUG | validated data: {'first_name': 'Ibraheeem', 'last_name': 'Khaleeel', 'email': 'ibrahee@gmail.com', 'user_name': 'ibrahikhaleel'}
ERROR | Internal Server Error: /note/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR | Internal Server Error: /note/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
DEBUG | validated data: {'first_name': 'Ibraheeem', 'last_name': 'Khaleeel', 'email': 'ibrahee@gmail.com', 'user_name': 'ibrahikhaleel'}
ERROR | Internal Server Error: /note/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note/
DEBUG | validated data: {'first_name': 'Ibraheeem', 'last_name': 'Khaleeel', 'email': 'ibrahee@gmail.com', 'user_name': 'ibrahikhaleel'}
WARNING | Bad Request: /note/
WARNING | Bad Request: /note-update/1/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/1/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/2/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/2/
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/2/
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note/
DEBUG | validated data: {'first_name': 'Ibraheeem', 'last_name': 'Khaleeel', 'email': 'ibrahee@gmail.com', 'user_name': 'ibrahikhaleel'}
WARNING | Bad Request: /note/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
DEBUG | validated data: {'first_name': 'Ibraheeem', 'last_name': 'Khaleeel', 'email': 'ibrahee@gmail.com', 'user_name': 'ibrahikhaleel'}
WARNING | Bad Request: /note/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
DEBUG | validated data: {'first_name': 'Ibraheeem', 'last_name': 'Khaleeel', 'email': 'ibrahee@gmail.com', 'user_name': 'ibrahikhaleel'}
WARNING | Bad Request: /note/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
DEBUG | validated data: {'first_name': 'Ibraheeem', 'last_name': 'Khaleeel', 'email': 'ibrahee@gmail.com', 'user_name': 'ibrahikhaleel'}
WARNING | Bad Request: /note/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 74, in delete
    label = Label.get_object(pk)
AttributeError: type object 'Label' has no attribute 'get_object'
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 74, in delete
    label = Label.self.get_object(pk)
AttributeError: type object 'Label' has no attribute 'self'
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 75, in delete
    label.delete()
AttributeError: 'Response' object has no attribute 'delete'
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 74, in delete
    label = self.get_object(id = pk)
TypeError: get_object() got an unexpected keyword argument 'id'
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 75, in delete
    label.delete()
AttributeError: 'Response' object has no attribute 'delete'
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 68, in put
    if serializer.is_valid():
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\serializers.py", line 419, in run_validation
    value = self.to_internal_value(data)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\serializers.py", line 476, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\fields.py", line 799, in run_validation
    return super().run_validation(data)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\fields.py", line 569, in run_validation
    self.run_validators(value)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\fields.py", line 591, in run_validators
    validator(value, self)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\validators.py", line 72, in __call__
    queryset = self.exclude_current_instance(queryset, instance)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\validators.py", line 60, in exclude_current_instance
    return queryset.exclude(pk=instance.pk)
AttributeError: 'Response' object has no attribute 'pk'
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\urls.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/1/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 61, in get
    label = Label.objects.get(pk)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\sql\query.py", line 1255, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable int object
ERROR | Internal Server Error: /label-update/1/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 61, in get
    label = Label.objects.get(pk)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\sql\query.py", line 1255, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable int object
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 61, in get
    label = Label.objects.get(pk)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\db\models\sql\query.py", line 1255, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable int object
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 77, in delete
    label.delete()
AttributeError: 'Response' object has no attribute 'delete'
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 77, in delete
    label.delete()
AttributeError: 'Response' object has no attribute 'delete'
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 77, in delete
    label.delete
AttributeError: 'Response' object has no attribute 'delete'
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 78, in delete
    label.delete()
AttributeError: 'Response' object has no attribute 'delete'
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /label-update/2/
WARNING | Bad Request: /label-update/2/
WARNING | Not Found: /favicon.ico
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
ERROR | Internal Server Error: /label-update/2/
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\views.py", line 68, in put
    if serializer.is_valid():
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\serializers.py", line 419, in run_validation
    value = self.to_internal_value(data)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\serializers.py", line 476, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\fields.py", line 799, in run_validation
    return super().run_validation(data)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\fields.py", line 569, in run_validation
    self.run_validators(value)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\fields.py", line 591, in run_validators
    validator(value, self)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\validators.py", line 72, in __call__
    queryset = self.exclude_current_instance(queryset, instance)
  File "C:\Users\Ibrahim Khaleel\Envs\venv\lib\site-packages\rest_framework\validators.py", line 60, in exclude_current_instance
    return queryset.exclude(pk=instance.pk)
AttributeError: 'Response' object has no attribute 'pk'
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/1/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/1/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
WARNING | Bad Request: /note-update/1/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\views.py changed, reloading.
DEBUG | Using proactor: IocpProactor
WARNING | Bad Request: /note/
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Label\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
>>>>>>> UC-5-NotesAndLabelCRUD
DEBUG | Using proactor: IocpProactor
INFO | C:\Users\Ibrahim Khaleel\VisualStudioProjects\djangoprojects\fundoonote\myfundoonote\Notes\models.py changed, reloading.
DEBUG | Using proactor: IocpProactor
